CREATE TABLE Sede
    (
        Codigo_sede NUMBER GENERATED BY DEFAULT AS IDENTITY
        START WITH 1 PRIMARY KEY,
        Nombre_sede VARCHAR2(50) NOT NULL
    );
 
CREATE TABLE Carrera
  (
    Codigo_carrera NUMBER PRIMARY KEY  ,
    Nombre_carrera VARCHAR2( 50 ) NOT NULL,
    Sede_codigo_sede NUMBER NOT NULL,                
    CONSTRAINT fk_sede_carrera FOREIGN KEY( Sede_codigo_sede )
      REFERENCES Sede( codigo_sede ) 
      ON DELETE CASCADE
  );
 
 ------------------ creada
CREATE TABLE Curso
  (
    Codigo_curso NUMBER PRIMARY KEY,
    Nombre_carrera VARCHAR2( 50 ) NOT NULL,
    Carrera_pertenece VARCHAR2( 50 ) NOT NULL,
    Semestre VARCHAR2( 50 ) NOT NULL,
    Pre_requisito VARCHAR2( 50 ) NOT NULL,
    Carrera_codigo_carrera NUMBER NOT NULL,                
    CONSTRAINT fk_carrera_curso FOREIGN KEY( Carrera_codigo_carrera )
      REFERENCES Carrera( Codigo_carrera ) 
      ON DELETE CASCADE,
      Asignacion_codigo_asigancion NUMBER NOT NULL,                
    CONSTRAINT fk_curso_asignacion FOREIGN KEY( Asignacion_codigo_asigancion )
      REFERENCES Asignacion( Codigo_asignacion ) 
      ON DELETE CASCADE
  );


--creada
CREATE TABLE Ciclo
  (
    Codigo_ciclo NUMBER PRIMARY KEY,
    Anio NUMBER NOT NULL,
    Semestre VARCHAR2(50) NOT NULL, 
    Curso_disponible VARCHAR2(50) NOT NULL,
    Curso_codigo_curso NUMBER NOT NULL,
    CONSTRAINT fk_Ciclo_curso FOREIGN KEY( Curso_codigo_curso )
      REFERENCES Curso( Codigo_curso ) 
      ON DELETE CASCADE
  );
 ---creada
CREATE TABLE Catedratico
  (
    Codigo_catedratico NUMBER PRIMARY KEY,
    Nombre VARCHAR2(50) NOT NULL,
    Apellido VARCHAR2(50) NOT NULL, 
    Curso_imparte VARCHAR2(50) NOT NULL,
    Curso_codigo_curso NUMBER NOT NULL,
    CONSTRAINT fk_Catedratico_curso FOREIGN KEY( Curso_codigo_curso )
      REFERENCES Curso( Codigo_curso ) 
      ON DELETE CASCADE
  );

--creada
CREATE TABLE Tipo_pago
  (
    Codigo_tipo_pago NUMBER PRIMARY KEY,
    Inscripcion VARCHAR2( 50 ) NOT NULL,
    Mensualidad NUMBER NOT NULL, 
    Examen_extraordinario VARCHAR2( 50 ) NOT NULL,
    Mora NUMBER NOT NULL,
    Pago_codigo_pago NUMBER NOT NULL,
    CONSTRAINT fk_pago_tipo_pago FOREIGN KEY( Pago_codigo_pago )
      REFERENCES Pago( Codigo_pago ) 
      ON DELETE CASCADE
  ); 


--creada
 CREATE TABLE Pago
    (
        Codigo_pago NUMBER PRIMARY KEY,
        Carne_estudiante NUMBER NOT NULL,
        Tipo_pago VARCHAR2(50)NOT NULL,
        Mes VARCHAR2(50) NOT NULL,
        Estudiante_carne NUMBER NOT NULL,
        CONSTRAINT fk_Estudiante_pago FOREIGN KEY( Estudiante_carne )
        REFERENCES Estudiante( Carne ) 
        ON DELETE CASCADE
    );


-- creada
 CREATE TABLE Estudiante
    (
        Carne NUMBER GENERATED BY DEFAULT AS IDENTITY
        START WITH 1 PRIMARY KEY,
        Nombre VARCHAR2(50)NOT NULL,
        Apellido VARCHAR2(50) NOT NULL,
        Fecha_nacimiento DATE NOT NULL,
        Doc_identificacion NUMBER NOT NULL
    );
   
--creada
 CREATE TABLE Nota
    (
        Codigo_estudiante NUMBER PRIMARY KEY,
        Curso VARCHAR2(50) NOT NULL,
        Actividades NUMBER NOT NULL,
        Primer_parcial NUMBER NOT NULL,
        Segundo_parcial NUMBER NOT NULL,
        Examen_final NUMBER NOT NULL,
        Catedratico_codigo_catedratico NUMBER NOT NULL,
        CONSTRAINT fk_Nota_catedratico FOREIGN KEY( Catedratico_codigo_catedratico )
        REFERENCES Catedratico( Codigo_catedratico ) 
        ON DELETE CASCADE,
        Estudiante_carne NUMBER NOT NULL,
        CONSTRAINT fk_Nota_estudiante FOREIGN KEY( Estudiante_carne )
        REFERENCES Estudiante( Carne ) 
        ON DELETE CASCADE
    );
   
   
--creada
 CREATE TABLE Usuario
    (
        Codigo_usuario NUMBER PRIMARY KEY,
        Tipo_usuario VARCHAR2(50) NOT NULL,
        Estado VARCHAR2(50)NOT NULL,
        Rol VARCHAR2(50)NOT NULL,
        Estudiante_carne NUMBER NOT NULL,
        CONSTRAINT fk_Usuario_estudiante FOREIGN KEY( Estudiante_carne  )
        REFERENCES Estudiante( Carne ) 
        ON DELETE CASCADE,
        Catedratico_codigo_catedratico NUMBER NOT NULL,
        CONSTRAINT fk_Usuario_catedratico FOREIGN KEY( Catedratico_codigo_catedratico  )
        REFERENCES Catedratico( Codigo_catedratico ) 
        ON DELETE CASCADE
    ); 

--creada
CREATE TABLE Rol
    (
        Codigo_rol NUMBER PRIMARY KEY,
        Codigo_usuario NUMBER NOT NULL,
        Estado VARCHAR2(50)NOT NULL,
        Fecha_creacion DATE NOT NULL,
        Usuario_codigo_usuario NUMBER NOT NULL,
        CONSTRAINT fk_Rol_usuario FOREIGN KEY( Usuario_codigo_usuario  )
        REFERENCES Usuario( Codigo_usuario ) 
        ON DELETE CASCADE
    );     
  
  
--creada
 CREATE TABLE Inscripcion
    (
        Codigo_inscripcion NUMBER PRIMARY KEY,
        Fecha DATE NOT NULL,
        Carrera VARCHAR2(50)NOT NULL,
        Ciclo NUMBER NOT NULL,
        Estudiante_carne NUMBER NOT NULL,
        CONSTRAINT fk_Inscrpcion_estudiante FOREIGN KEY( Estudiante_carne  )
        REFERENCES Estudiante( Carne ) 
        ON DELETE CASCADE
    );    
  
  
  --creada  
 CREATE TABLE Asignacion
    (
        Codigo_asignacion NUMBER PRIMARY KEY,
        Codigo_carrera NUMBER NOT NULL,
        Codigo_curso NUMBER NOT NULL,
        Codigo_extra VARCHAR2(50) NOT NULL,
        Inscripcion_codigo_inscripcion NUMBER NOT NULL,
        CONSTRAINT fk_Inscrpcion_asignacion FOREIGN KEY( Inscripcion_codigo_inscripcion  )
        REFERENCES Inscripcion( Codigo_inscripcion ) 
        ON DELETE CASCADE
    );     

  