Select * from dba_users;

--CREAR TABLESPACE
CREATE TABLESPACE "TSTABLAUSUARIOS"
DATAFILE 'C:\app\usuario\product\21c\oradata\XE\UMGPROYEC.DBF' SIZE 200M;

--TABLESPACE TEMPORAL
CREATE TEMPORARY TABLESPACE "TSTABLAUSUARIOS_TEMP" TEMPFILE 'C:\app\usuario\product\21c\oradata\XE\TSTABLAUSUARIOS_TEMP.DBF'  SIZE 200M;

-- Crear usuario
CREATE USER SECRETARIA IDENTIFIED BY umg123;
CREATE USER CATEDRATICO IDENTIFIED BY umg123;
CREATE USER TESORERIA IDENTIFIED BY umg123;

--dejar conectar al usuario
GRANT CONNECT TO SECRETARIA;
GRANT CONNECT TO CATEDRATICO;
GRANT CONNECT TO TESORERIA;

--ACCESO AL SISTEMA
GRANT RESOURCE TO SECRETARIA;
GRANT RESOURCE TO CATEDRATICO;
GRANT RESOURCE TO TESORERIA;

--PRIVILEGIOS PARA LOS PRIVILEGIOS A LOS USUARIOS
GRANT SELECT ON ADMIN123.ESTUDIANTE TO SECRETARIA;
GRANT SELECT, INSERT, UPDATE ON ADMIN123.ESTUDIANTE TO SECRETARIA;
GRANT EXECUTE ON ADMIN123.PA_INSERT_ESTUDIANTE TO SECRETARIA;
